sudo: false
language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

services:
  - postgresql
addons:
  postgresql: 9.6

before_install: gem install bundler -v 1.16.1
before_script:
  - psql -c 'create database sequel_connection_guard;' -U postgres
script:
  - bundle exec rspec
  - bundle exec rubocop

cache: bundler
